### ISSUE TITLE
Add PPA for HAProxy error bookworm version

### ISSUE THREAD

**Issue by cnaslain** [hifis-net/ansible-role-haproxy#125]
Hi,

Trying to install/setup an HAproxy instance on a rasperry pi. I use an ansible docker image `alpine/ansible` (`ansible 2.10.5` and `python version = 3.8.8`). The remote raspberry pi server: `cat /etc/debian_version = debian 12.2` (bookworm).

I get this error:
```
TASK [ansible-role-haproxy : Add PPA for HAProxy] *******************************************************************************************
fatal: [pi4pool.naslain.com]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'http://ppa.launchpad.net/vbernat/haproxy-2.8/ubuntu bookworm Release' does not have a Release file., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:https://download.docker.com/linux/debian/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details."}
```

From https://launchpad.net/~vbernat/+archive/ubuntu/haproxy-2.6 I see no repo for the bookworm version. Is this the reason why it fails?

Another question: Is there any configuration to bypass the PPA repo addition and use the default bookworm repo haproxy package?

Regards,

Chris

**Comment by cnaslain** [comment]
See https://github.com/hifis-net/ansible-role-haproxy/pull/126 PR for an alternative option.
Feel free to adapt this upon your needs.

**Comment by Normo** [comment]
Thanks @cnaslain.

> From https://launchpad.net/~vbernat/+archive/ubuntu/haproxy-2.6 I see no repo for the bookworm version. Is this the reason why it fails?

Yes, this PPA is only intended for Ubuntu. For Debian you have to enable a dedicated repository to install the latest stable HAProxy version (http://haproxy.debian.net) .

**Comment by cnaslain** [comment]
Thanks for your reply. Any way to adapt the role for this ubuntu/debian switch?
In both cases, your recommendation is to add an haproxy dedicated repo.

**Comment by Normo** [comment]
> Any way to adapt the role for this ubuntu/debian switch?
> In both cases, your recommendation is to add an haproxy dedicated repo.

We are using the role on Ubuntu only at the moment, but there is no reason not to support Debian by enabling the HAProxy apt repository as well. 
Feel free to create a Pull Request (#127).
